### ISSUE TITLE
MakeDiploidFSTMat Error X 2

### ISSUE THREAD

**Issue by tunaloveheart** [whitlock/OutFLANK#7]
Dear Micheal and Katie

Hoping you could take a look at this issue below and help me out. Got it working, then R crashed, now even after reinstalling the packages and updating still cant get it to work. 

> FSTmat<- MakeDiploidFSTMat(SNPmat=SNPmat, locusNames=locusNames, popNames=as.character(pops))

Error in tapply(snpDataTemp, list(popNameTemp, snpDataTemp), length) : 
  arguments must have same length

So we try to transpose matrix... because of conflicting data input information between (a) OUTFLANK readme pdf and ?MakeDiploidFSTMat

SNPmat<- t(SNPmat)

> FSTmat<- MakeDiploidFSTMat(SNPmat=SNPmat, locusNames=locusNames, popNames=as.character(pops))
[1] "Error: your population names do not match your SNP matrix"
Error in MakeDiploidFSTMat(SNPmat = SNPmat, locusNames = locusNames, popNames = as.character(pops)) : 
  no loop for break/next, jumping to top level

Please find attached my **genotype data file** and **locusNames** and **pops** 
[OutFLANK_data.txt](https://github.com/whitlock/OutFLANK/files/1196071/OutFLANK_data.txt)
[locusNames_OF.txt](https://github.com/whitlock/OutFLANK/files/1196073/locusNames_OF.txt)
[popNames_OF.txt](https://github.com/whitlock/OutFLANK/files/1196074/popNames_OF.txt)

**Comment by DrK-Lo** [comment]
Hello,

OutFLANK uses a 9 for missing data, as described in the pdf. When I fixed your data, it worked just fine. That is because NAs are removed by the algorithm, resulting in a different length between your vectors.

library(OutFLANK)
o <- read.table("OUTFLANK_data.txt")
dim(o)
p <- read.csv("popNames_OF.txt")
head(p)
l <- read.csv("locusNames_OF.txt")
head(l)

# Use 9 for missing data
sum(is.na(o)) # should not contain NAs
o2 <- o
o2[is.na(o2)] <- 9
sum(is.na(o2))
dim(o2)
levels(factor(as.numeric(unlist(o2))))

out <- MakeDiploidFSTMat(SNPmat=o2, locusNames=l$x, popNames=p$x)

out <- MakeDiploidFSTMat(SNPmat=o, locusNames=l$x, popNames=p$x)
	# replicate error when use NA for missing data

**Comment by tunaloveheart** [comment]
Hey Katie

Thanks so much I knew it would be something stupid. When R crashed I mustn't  have saved the right data frame which worked the first time because I change the NA to 9. Thanks again and sorry for my stupid question!! 

Dani

**Comment by saarman** [comment]
Thanks I had the same problem. using plink --recodeA gives a genotype matrix with NA, thus this problem. Could you place this conversion of formats [is.na(genotype)] <- 9 in the vignette so that people without a bunch of experience in R can fix their input files to match this non-standard format (i.e. 9 instead of NA)?

**Comment by Andrinajoro** [comment]
hi there, followed your advice by changing "NA" by "9" and still getting the following error 
"Loading SNPmat...
Loading popNames...
Loading locusNames...

=== DIAGNOSTIC CHECKS ===
SNPmat:       757 loci x 66 individuals
popNames:     66 entries
locusNames:   757 entries
Sample order matches?  TRUE 
Locus order matches?   TRUE 

=== RUNNING OutFLANK ===
[1] "Error: your population names do not match your SNP matrix"
Error in MakeDiploidFSTMat(SNPmat = SNPmat, locusNames = locusNames, popNames = popNames) : 
  no loop for break/next, jumping to top level
Execution halted".

Your help would be much appreciated!
Please find attached my genotype data file and locusNames and pops

[locusNames_for_OutFLANK.txt](https://github.com/user-attachments/files/24128296/locusNames_for_OutFLANK.txt)
[popNames_for_OutFLANK.txt](https://github.com/user-attachments/files/24128295/popNames_for_OutFLANK.txt)
[SNPmat_for_OutFLANK.csv](https://github.com/user-attachments/files/24128294/SNPmat_for_OutFLANK.csv)

[GENOTYPE_individuals_x_loci.csv](https://github.com/user-attachments/files/24128304/GENOTYPE_individuals_x_loci.csv)
